### ISSUE TITLE
Encoder Errors

### ISSUE THREAD

**Issue by seandenigris** [PortingPDFtalk/PharoPDFtalk#3]
Sven confirmed that the text converters (e.g. UTF16TextConverter) have been superseded by the Zinc encoders ([via Discord](https://discord.com/channels/223421264751099906/223421264751099906/986207417241067571)). cc/ @ChristianHaider

**Comment by ChristianHaider** [comment]
Thanks! Integrated.

**Comment by ChristianHaider** [comment]
Should work in the latest version
